const n=id=>parseFloat(document.getElementById(id)?.value)||0;const rup=v=>'Rp '+Math.round(v).toLocaleString('id-ID');
function calcConcrete(){const l=n('c_l'),w=n('c_w'),h=n('c_h'),q=n('c_q')||1,cost=n('c_cost');const v=l*w*h*q;document.getElementById('c_result').innerHTML=`<strong>${v.toFixed(3)} m³</strong><br>Volume beton. Estimasi biaya: ${rup(v*cost)}.`}
function calcWall(){const a=n('w_l')*n('w_h'),o=n('w_open'),net=Math.max(0,a-o),per=n('w_per')||1,unit=n('w_unit')||70,cost=n('w_cost');const qty=Math.ceil(net*unit*per);document.getElementById('w_result').innerHTML=`<strong>${qty.toLocaleString('id-ID')} pcs</strong><br>Estimasi kebutuhan bata termasuk waste. Biaya: ${rup(qty*cost)}.`}
function calcFloor(){const a=n('f_l')*n('f_w'),w=n('f_waste')/100,box=n('f_box')||1,cost=n('f_cost');const total=a*(1+w),qty=Math.ceil(total/box);document.getElementById('f_result').innerHTML=`<strong>${qty} dus</strong><br>Luas kebutuhan ${total.toFixed(2)} m². Estimasi: ${rup(qty*cost)}.`}
function calcRoof(){const l=n('r_l'),w=n('r_w'),ang=n('r_ang')*Math.PI/180,waste=n('r_waste')/100,cost=n('r_cost');const plan=l*w,area=plan/Math.cos(ang)*(1+waste);document.getElementById('r_result').innerHTML=`<strong>${area.toFixed(2)} m²</strong><br>Estimasi luas penutup atap + waste. Biaya: ${rup(area*cost)}.`}
function calcPaint(){const wall=n('p_wall'),ceil=n('p_ceil'),coat=n('p_coat')||2,cover=n('p_cover')||10,waste=n('p_waste')/100,cost=n('p_cost');const liters=(wall+ceil)*coat/cover*(1+waste);document.getElementById('p_result').innerHTML=`<strong>${liters.toFixed(1)} liter</strong><br>Estimasi cat untuk ${coat} lapis. Biaya: ${rup(liters*cost)}.`}
function addRab(){const tbody=document.querySelector('#rabBody'),tr=document.createElement('tr');tr.innerHTML='<td><input placeholder="Item"></td><td><input type="number" value="1" step="0.01"></td><td><input placeholder="unit"></td><td><input type="number" value="0"></td><td class="sub">Rp 0</td><td><button type="button" class="btn btn-outline del">Hapus</button></td>';tbody.appendChild(tr);tr.querySelectorAll('input').forEach(x=>x.addEventListener('input',sumRab));tr.querySelector('.del').onclick=()=>{tr.remove();sumRab()};sumRab()}
function sumRab(){let total=0;document.querySelectorAll('#rabBody tr').forEach(tr=>{const q=parseFloat(tr.cells[1].querySelector('input').value)||0,p=parseFloat(tr.cells[3].querySelector('input').value)||0,s=q*p;total+=s;tr.querySelector('.sub').textContent=rup(s)});const o=n('rabOver')/100,pr=n('rabProfit')/100;document.getElementById('rabTotal').textContent=rup(total*(1+o)*(1+pr))}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-calc]').forEach(b=>b.addEventListener('click',()=>window[b.dataset.calc]?.()));document.getElementById('addRab')?.addEventListener('click',addRab);document.querySelectorAll('#rabBody input,#rabOver,#rabProfit').forEach(x=>x.addEventListener('input',sumRab));addRab()});
